spring:
  datasource:
    hikari:
      connection-timeout: ${DB_CONNECTION_TIMEOUT:20000}
      maximum-pool-size: ${DB_MAXIMUM_POOL_SIZE:5}
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
app:
  env: development
jwt:
  secret: ${JWT_SECRET}
  expirationInMilliseconds: 86400000
auth:
  disableCsrf: true
token:
  resetPassword:
    intervalInMilliseconds: 30000
    maxAgeInMilliseconds: 300000
