name: Deploy
on:
  workflow_run:
    workflows: [ 'Build' ]
    branches: [ main ]
    types:
      - completed
jobs:
  deploy:
    # only run if the build job was successful
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Create env file
        run: touch .env && echo "${{ secrets.ENV_FILE }}" > .env
      - name: Copy env file to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          port: ${{ secrets.DEPLOY_PORT }}
          source: .env
          target: /
      - name: Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            docker pull cyberproton/ocean-backend-spring:latest
            CONTAINER_NAME=ocean
            if [ "$(docker ps -qa -f name=$CONTAINER_NAME)" ]; then if [ "$(docker ps -q -f name=$CONTAINER_NAME)" ]; then echo "Container is running -> stopping it..." && docker stop $CONTAINER_NAME; fi fi
            docker run -d --rm --env-file .env -p 8000:8000 --name $CONTAINER_NAME cyberproton/ocean-backend-spring:latest